#!/bin/sh

# ref. http://ameblo.jp/yakisoba-panman/entry-10026112918.html

xjoypad -buttons 54 55 40 41 26 27 
xjoypad -left 43 
xjoypad -right 46 
xjoypad -up 45 
xjoypad -down 44

# common key keycode (you can seek using xev)
# [↑] : 98
# [↓] : 104
# [←] : 100
# [→] : 102
# [Enter] : 36
# [Space] : 65
# [Tab] : 23
# [A] : 38
# [S] : 39
# [D] : 40
# [Z] : 52
# [X] : 53
# [C] : 54
