#!/bin/sh

if (( $# == 1 )); then
    case $1 in
        "usb" )
            sudo modprobe rndis_host
            sudo /etc/init.d/net.usb0 start
            sudo /etc/init.d/net.wlan0 stop
            exit 0 ;;
        "wlan" )
            sudo /etc/init.d/net.usb0 stop
            sudo /etc/init.d/net.wlan0 start
            exit 0 ;;
        "home" )
            sudo /etc/init.d/net.usb0 stop
            sudo /etc/init.d/net.wlan0 start
            sudo wpa_cli select_network 5
            exit 0 ;;
        "phone" )
            sudo /etc/init.d/net.usb0 stop
            sudo /etc/init.d/net.wlan0 start
            sudo wpa_cli select_network 0
            exit 0 ;;
        "stop" )
            sudo /etc/init.d/net.wlan0 stop
            sudo /etc/init.d/net.usb0 stop
            exit 0 ;;
    esac
    echo "undetermined operation"
    exit 1 
else
    echo "need one param"
    exit 1
fi
