#!/bin/sh

hdmi_res="1920x1080"
lvds_res="1366x768"

if (( $# == 1 )); then
    case $1 in
        "hdmi-mirror" )
            xrandr --output HDMI1 --mode $hdmi_res --output LVDS1 --mode $lvds_res ;;
        "hdmi-left" )
            xrandr --output HDMI1 --mode $hdmi_res --left-of LVDS1 --output LVDS1 --mode $lvds_res ;;
        "hdmi-right" )
            xrandr --output HDMI1 --mode $hdmi_res --right-of LVDS1 --output LVDS1 --mode $lvds_res ;;
        "hdmi-off" )
            xrandr --output HDMI1 --off
    esac
fi
